import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const itemClass = 'sidebar-item-animated';
const categoryClass = 'sidebar-category-animated';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for curriculum overview
  curriculumSidebar: [
    {type: 'doc', id: 'Introduction', className: itemClass},
    {type: 'doc', id: 'Setup-Guide', className: itemClass},
    {type: 'doc', id: 'Overview-Module-and-Chapter', className: itemClass},
    {
      type: 'category',
      label: 'Module 1: ROS2 Foundations',
      className: categoryClass,
      collapsed: false,
      items: [
        {type: 'doc', id: 'Module-1-ROS2/Introduction-to-Physical-AI', className: itemClass},
        {type: 'doc', id: 'Module-1-ROS2/Embodied-Intelligence-and-Sensors', className: itemClass},
        {type: 'doc', id: 'Module-1-ROS2/ROS2-Architecture', className: itemClass},
        {type: 'doc', id: 'Module-1-ROS2/Nodes-Topics-Services', className: itemClass},
        {type: 'doc', id: 'Module-1-ROS2/ROS2-Packages-and-Launch-Files', className: itemClass}
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twins',
      className: categoryClass,
      collapsed: false,
      items: [
        {type: 'doc', id: 'Module-2-Digital-Twin/glossary', className: itemClass},
        {type: 'doc', id: 'Module-2-Digital-Twin/diagram-layout', className: itemClass},
        {type: 'doc', id: 'Module-2-Digital-Twin/style-guide', className: itemClass},
        {type: 'doc', id: 'Module-2-Digital-Twin/troubleshooting', className: itemClass},
        {type: 'doc', id: 'Module-2-Digital-Twin/code-example-template', className: itemClass},
        {type: 'doc', id: 'Module-2-Digital-Twin/Gazebo-Setup-and-Simulation', className: itemClass},
        {type: 'doc', id: 'Module-2-Digital-Twin/URDF-Physics-and-Unity', className: itemClass}
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI Robot Brain',
      className: categoryClass,
      collapsed: false,
      items: [
        {type: 'doc', id: 'Module-3-AI-Robot-Brain/common-template', className: itemClass},
        {type: 'doc', id: 'Module-3-AI-Robot-Brain/NVIDIA-Isaac-Platform', className: itemClass},
        {type: 'doc', id: 'Module-3-AI-Robot-Brain/Perception-and-Manipulation', className: itemClass},
        {type: 'doc', id: 'Module-3-AI-Robot-Brain/Reinforcement-Learning-and-Sim-to-Real', className: itemClass}
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      className: categoryClass,
      collapsed: false,
      items: [
        {type: 'doc', id: 'Module-4-Vision-Language-Action/Humanoid-Kinematics-and-Locomotion', className: itemClass},
        {type: 'doc', id: 'Module-4-Vision-Language-Action/Manipulation-and-Human-Robot-Interaction', className: itemClass},
        {type: 'doc', id: 'Module-4-Vision-Language-Action/Conversational-Robotics', className: itemClass}
      ],
    },
    {
      type: 'category',
      label: 'Reference Materials',
      className: categoryClass,
      collapsed: false,
      items: [
        {type: 'doc', id: 'Reference', className: itemClass},
        {type: 'doc', id: 'Capstone', className: itemClass},
        {type: 'doc', id: 'Conclusion', className: itemClass}
      ],
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
